apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test1
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mkosiarc-tenant/test1/test1@sha256:81c42ce81751814cdde4009c735337f42bd3927e6e9e2cba318010c223a2cb2c
        name: container-image
        resources: {}
status: {}
