apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test1
    app.kubernetes.io/part-of: test1
  name: test1
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: test1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test1
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mkosiarc-tenant/test1/test1@sha256:81c42ce81751814cdde4009c735337f42bd3927e6e9e2cba318010c223a2cb2c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
