apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test1
    app.kubernetes.io/part-of: test1
  name: test1
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: test1
status:
  loadBalancer: {}
